### ISSUE TITLE
(real) random and repeat

### ISSUE THREAD

**Issue by mlaggner** [sturple/textrotator#1]
I've just found your rotator and find it really nice.
There are just two findings:

a) random should be a _real_ random: random picking every li rather than only start random
b) you should integrate a repeat function: after the last li has been hidden nothing is shown any more

thanks
Manuel

**Comment by sturple** [comment]
Hi Manuel,
Thanks for the feedback,
I am meaning to update the textrotator, and  will look into your 
considerations.

Regards,
Shawn

**Comment by sturple** [comment]
This has been fixed in the first release of this product V0.0.1
https://github.com/sturple/textrotator/releases
